### ISSUE TITLE
Add Mockito 3 to 4 migration

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#186]
- https://github.com/mockito/mockito/releases/tag/v4.0.0
 - https://github.com/mockito/mockito/releases/tag/v4.1.0
 - https://github.com/mockito/mockito/releases/tag/v4.2.0
 - https://github.com/mockito/mockito/releases/tag/v4.3.0
 - https://github.com/mockito/mockito/releases/tag/v4.3.0

**Comment by timtebeek** [comment]
There have been [a few more releases](https://github.com/mockito/mockito/releases) since this issue was opened; Mockito is now at 4.7.0.
4.0.0 dropped a number of deprecated APIs; which are [already covered in the 3.x migration](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/mockito.yml#L28). 

The only other deprecation since was in 4.5.0 with [Listutil and Fields classes](https://github.com/mockito/mockito/pull/2593), but both of these classes were in `org.mockito.internal.util`, so not part of the public API.

That means that for now at least there are no further required steps (apart from the dependency) to upgrade to 4.7.0, with any next required migration steps likely to roll over into a 5.x migration.

There's already a placeholder 4.x migration, which might only need [a dependency version upgrade](https://github.com/openrewrite/rewrite-testing-frameworks/blob/3397a953f18e42c7e3897f8b124085cca0969117/src/main/resources/META-INF/rewrite/mockito.yml#L99), which might not even need a pull request.

**Comment by pway99** [comment]
Thanks Tim! I renamed the existing `Mockito3To4Migration` to Mockito1To4Migration`since the recipe already referenced the 1To3Migration.  I also added a Maven Dependency upgrade for Mockito 4.x and updated the JUnit 4To5 reference.

**Comment by timtebeek** [comment]
Great to see this one resolved. Should be nice to see the 4.x line picked up.:)

**Comment by pway99** [comment]
For sure, thanks again for your help :)
