### ISSUE TITLE
JUnit5 StaticImports incorrectly removes static import of `Assertions.assertTrue`

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#276]
`org.openrewrite.java.testing.junit5.StaticImports` removes `import static org.junit.jupiter.api.Assertions.assertTrue;` in a test class of ours, with relevant bits copied here:
```diff
-import static org.junit.jupiter.api.Assertions.assertTrue;

class FooTest {
	private TestOutputTopic<String, Foo> rejectedFooTopic;
	@Test
	void rejected() {
		assertTrue(rejectedFooTopic.isEmpty());
	}
```
This leads to compilation errors, and makes it harder to enforce there's no new non static imports on our projects.

**Comment by traceyyoshima** [comment]
Hi @timtebeek, I think this is fixed on the main branch via https://github.com/openrewrite/rewrite/commit/d236def5368d84e0e995d9ff00232d1595b5dc13 in `rewrite`.

I ran the StaticImports recipe on the sample code, and the import was not removed.
Would you please confirm if your issue is fixed? I appreciate any help you can provide.

**Comment by timtebeek** [comment]
Hi Tracey, soonest I can check this myself would be January 2nd, but you're welcome to close this issue already based on your tests. :)

**Comment by traceyyoshima** [comment]
@timtebeek, alright, sounds good -- thanks!

Closing the issue. The issue should be fixed by the commit referenced in the comments and is not reproducible.
