### ISSUE TITLE
Recipe that ensures that the static import for AssertJ Assertions is always used.

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-testing-frameworks#31]
To avoid a bunch of these in the test code:

![image](https://user-images.githubusercontent.com/1697736/105609614-5ab4b280-5d5f-11eb-9124-db2351f253aa.png)

**Comment by aegershman** [comment]
To clarify, which of these is the goal:

- **always** convert a qualified name of `Assertions.{someMethod...}` to the static method, regardless of whether the static import already exists. For example, always convert uses of the qualified `Assertions.someMethod` to static `someMethod`. Always.

OR

- **IF** the static method in question is _already imported_, then make sure that static method is used in all places where the qualified name is being used? For example, if `assertThat` is already statically imported, then convert any other uses of `Assertions.assertThat` in the file to be static. However, if static `assertThat` is NOT already imported, and all existing usages are qualified as `Assertions.assertThat`, then leave it be.

**Comment by sambsnyd** [comment]
All imports of AssertJ methods should be static imports.
All invocations of AssertJ methods should be the receiver-less form you can only use when a static import for the method is present.

**Comment by aegershman** [comment]
Wait, couldn't this just be done as-is with a normal `UseStaticImport`? https://github.com/openrewrite/rewrite-docs/blob/926f06a694cab31b2566d0f7c92c572cfaf5d4a5/reference/java/refactoring-java-source-code/usestaticimport.md

(source for it: https://github.com/openrewrite/rewrite/blob/8e9ccb2b4796deee48c17b244f31733b3962c5e2/rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java)

I'll test this, but shouldn't this do everything?

```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.UseStaticAssertJAssertions
recipeList:
  - org.openrewrite.java.UseStaticImport:
    method: 'org.assertj.core.api.Assertions *(..)'
```

If this _does_ work, then I think this would be acceptable, right? Since this is stylistic, I don't know if we should package this in as it's own file shipped with the framework, but if we did, I could just put it in `META-INF.rewrite/use-static-assertj-assertions.yaml`

**Comment by aegershman** [comment]
closed by https://github.com/openrewrite/rewrite-testing-frameworks/pull/38

Is referenced as part of...

```
<recipe>org.openrewrite.java.testing.JUnit5AssertionsToAssertJMigration<recipe>
```
