### ISSUE TITLE
Migrate to Spring Boot 2 from Spring Boot 1 recipe fails to migrate ClassRule

### ISSUE THREAD

**Issue by thatdc-reply** [openrewrite/rewrite-testing-frameworks#332]
I am trying to run the Migrate to Spring Boot 2 from Spring Boot 1 recipe, to migrate my legacy application from Springboot 1.5.2 to Springboot 2.7.x. 
I am facing a problem with the testing framework. I execute the aforementioned recipe with `mvn rewrite:dryRun` and I obtain something like this in the patch file.

```
 		<dependency>
-			<groupId>junit</groupId>
-			<artifactId>junit</artifactId>
+			<groupId>org.junit.jupiter</groupId>
+			<artifactId>junit-jupiter</artifactId>
 			<scope>test</scope>
 		</dependency>

[...]

-import org.junit.Before;
-import org.junit.ClassRule;
-import org.junit.FixMethodOrder;
-import org.junit.Test;
-import org.junit.runner.RunWith;
-import org.junit.runners.MethodSorters;
+import org.junit.ClassRule;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.MethodOrderer.MethodName;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.TestMethodOrder; 
```

Basically the recipe does not upgrate to something "jupitish" the ClassRule annotation from jUnit. Also, the dependency for jUnit has been removed, hence I deduce that there should be something to replace `junit.ClassRule`.
If I try to `mvn install` the application, I get the obvious error: `IdentitiesLdapMs5Test.java:[7,17] cannot find symbol
  symbol:   class ClassRule
  location: package org.junit`.

The usage of ClassRule in my project is the following:
```
@ClassRule
public static final JwtReader jwtReader = new JwtReader("jwt_tests.csv");
```

**Comment by timtebeek** [comment]
hi @thatdc-reply ; thanks for reporting this issue here! From what I gather in your report we failed to convert a `@ClassRule JwtReader` to a JUnit Jupiter equivalent construct. Could you tell me what dependency that `JwtReader` class is from?

OpenRewrite can typically only convert known ClassRules into JUnit Jupiter constructs, [such as we do here for instance for TemporaryFolder](https://docs.openrewrite.org/reference/recipes/java/testing/junit5/temporaryfoldertotempdir). This is because there's no clear one to one way to converting just any class rule to for instance a Jupiter extension. It could be that your `JwtReader` would require a similar migration recipe to only then be automatically migrated.

We do not currently support adding the junit-vintage-runner when we encounter a ClassRule that we do not yet support; that could be an alternative to keep your code working without migrating the JwtReader just yet. That would however keep you stuck on the 2.x branch of Spring Boot, as the 3.x branch drops support for JUnit 4.

**Comment by timtebeek** [comment]
I'm going to close this one due to inactivity, because I can not find any reference to a public `JwtReader` JUnit rule. Without details about that class we can not implement a recipe, and in any case such a recipe would be specific to that class, which is unlikely to be used or applicable elsewhere.

Do reach out if you'd like help developing such a migration recipe yourself!
