### ISSUE TITLE
JUnit 4 -> JUnit 5 migration - assertArrayEquals

### ISSUE THREAD

**Issue by puskarpeter** [openrewrite/rewrite-testing-frameworks#383]
## What problem are you trying to solve?

When migrating assertEquals, detect properly when to use assertArrayEquals.
I believe that between JUnit4 and JUnit5 assertEquals behaviour changed. It compares direct object references now.
The following test case below passes in JUnit4 but fails with JUnit5 assertEquals.
We are comparing two Object[]. Therefore we should use assertArrayEquals instead.

## Describe the situation before applying the recipe

```java
assertEquals(Lists.newArrayList("Loopback0", "GigabitEthernet0/0/0/2")
                        .toArray(),
                AreaInterfaceReader.parseInterfaceIds(OUTPUT)
                        .stream()
                        .map(InterfaceKey::getId)
                        .toArray());
```

## Describe the situation after applying the recipe

```java
assertArrayEquals(Lists.newArrayList("Loopback0", "GigabitEthernet0/0/0/2")
                        .toArray(),
                AreaInterfaceReader.parseInterfaceIds(OUTPUT)
                        .stream()
                        .map(InterfaceKey::getId)
                        .toArray());
```

## Any additional context

I think currently it is not differentiated whether the compared types are just objects or arrays of objects.

**Comment by timtebeek** [comment]
Thanks for reporting this issue here and in Slack! Indeed looks like a case we had not consciously covered before, so great to have a sample and see if we can implement a quick fix; Would you be willing to help kick start development with a Draft pull request that adds `Assert.assertEquals(new Object[1], new Object[1]);` to [the unit test fro AssertToAssertionsTest](https://github.com/openrewrite/rewrite-testing-frameworks/blob/07d3c549974a9130b986b5b29bb6e8ce435078b4/src/test/java/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.java#L165-L169)? From there it should then be easy to step through with the debugger and potentially even contribute the fix.
