### ISSUE TITLE
Activate removal of System.out.println

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-testing-frameworks#406]
## What problem are you trying to solve?

Clean code

## Describe the solution you'd like

Enable https://docs.openrewrite.org/recipes/staticanalysis/removesystemoutprintln in this repository

## Have you considered any alternatives or workarounds?

Yes - manual removal of statements - https://github.com/openrewrite/rewrite-testing-frameworks/pull/405

## Additional context

Dogfooding rulez (I don't have a good link - do you?)

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

I have difficulties in a proper configuration of the tool and would like to leave it to experts.

**Comment by timtebeek** [comment]
Thanks for the suggestion @koppor ! We regularly use the Moderne platform to run recipes against all OpenRewrite repositories, such as for instance with this link: https://app.moderne.io/results/gn87ZoR0F
That allows us to quickly resolve such issues, but it is reactive (for now) rather than something we run on pull requests. We're working on a review flow, which should prevent new issues.

Hope you don't mind me closing this issue, as we're tracking this internally already, and it's unlikely to be applied specifically to rewrite-testing-frameworks, but rather in general across all openrewrite repositories through https://github.com/openrewrite/gh-automation

**Comment by koppor** [comment]
Closing is fine for me. In JabRef, we run the check on push, to gain fast feedback. Works better for us, because we have more external (drive-by) contributors than internal ones.
