### ISSUE TITLE
Incorrect migration path from `verifyZeroInteractions()` to `verifyNoInteractions()` in Mockito 3.x

### ISSUE THREAD

**Issue by DivyaMaddipudi** [openrewrite/rewrite-testing-frameworks#630]
## What version of OpenRewrite are you using?
I am using
- OpenRewrite v2.21.1

## How are you running OpenRewrite?
CLI

## What is the smallest, simplest way to reproduce the problem?
Description:
The migration guide incorrectly recommends using verifyNoInteractions() when migrating from verifyZeroInteractions() in Mockito 2.x to Mockito >= 3.x. The correct migration path should be to use verifyNoMoreInteractions() instead, as verifyZeroInteractions() was an alias for verifyNoMoreInteractions(), not a true guarantee of zero interactions.

## What did you expect to see?
The migratioN should recommend using verifyNoMoreInteractions() when migrating from verifyZeroInteractions() in Mockito 2.x to Mockito >= 3.x.

**Comment by timtebeek** [comment]
Thanks for logging the issue here! I'll capture some of the details shared via Slack here as well.

We likely need an additional recipe that runs before this declarative recipe, and is only active when coming from older Mockito versions.
https://github.com/openrewrite/rewrite-testing-frameworks/blob/c4ab9a5c5cd0c0e8a992a02bf9a5177d68638a1d/src/main/resources/META-INF/rewrite/mockito.yml#L135-L137

We had a similar such recipe up until recently: the same mechanism can be applied here, even if that one was removed:
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/625

The best way to kick off this work would be to copy one of the test classes here to a new `VerifyZeroInteractionsTest`, which has test cases coming from both 2.x and 3.x, and each time moving to the right replacement depending on the version you're coming from
https://github.com/openrewrite/rewrite-testing-frameworks/tree/main/src/test/java/org/openrewrite/java/testing/mockito

> if coming from Mockito < 3 then change from `verifyZeroInteractions` to `verifyNoMoreInteractions`
> if coming from Mockito 3+ then change from `verifyZeroInteractions` to `verifyNoInteractions` (as we do now)

Welcome to kick that off with just a couple of tests on a draft PR; it's easier for us to collaborate when there's a start.
