### ISSUE TITLE
JUnit 4 to 5 TestWatcher migration recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#70]
Recipe to convert JUnit 4 TestWatcher to the JUnit5 variant

JUnit-4
https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestWatcher.html

JUnit-5
https://junit.org/junit5/docs/5.4.0-RC2/api/org/junit/jupiter/api/extension/TestWatcher.html

**Comment by aegershman** [comment]
Here's a breakdown. First a proposed workflow, then sections on the problems at each step:

## proposed workflow:

- For any `TestWatcher` instantiation in a test class, create a private class in that same public class file which `implements TestWatcher` (using the name `VariableNameTestWatcherExtension`, maybe)
- Add `@ExtendWith(VariableNameTestWatcherExtension.class)` to the class the TestWatcher was originally implemented in
- Convert the corresponding junit 4 method signatures to the Junit 5 signatures where possible.
  - as for the signatures which don't correspond exactly (`starting`, `skipped`, etc.), add another `implements` with the corresponding `Lifecycle` handlers. Not 100% about this, we'll see.
- Cleanup; as in, remove the old JUnit 4 TestWatcher instantiation, etc.

---

## problem 0: moving from AbstractClass to Interface

- In JUnit 4, TestWatcher is an abstract class.
- In Junit 5, TestWatcher is an interface.
- This can be solved; just pointing it out

## problem 1: callback method equivalents

- In JUnit 4, the TestWatcher Rule API provides us with callback methods.
- Some of these callback methods are no longer present in JUnit 5.
- In JUnit 4, for example, we had "protected void failed", "Invoked when a test fails", which has a generally-analogous method in JUnit 5, "testFailed", "Invoked after a test has failed".
- But some callback methods are no longer present in JUnit 5's TestWatcher.
- For example, in JUnit 4 there was "starting", "Invoked when a test is about to start". In JUnit 5, however, TestWatcher only appears to have methods which deal with the results of tests; there is no "testStarting".
- We can still work around this.

## problem 2a: addition of ExtensionContext

- Hopefully not a big deal though since it wasn't already in-use

## problem 2b: moving from `Description` to `ExtensionContext.

- There are similarities in usage, though.

## problem 3: what of static access?

- Static access for variables moving around within/with/against TestWatcher and the test classes

## problem/solution 4: registration of ExtendWith

- Not really that much of a problem. Generally a solution.
- Best way to register the newly-minted class which implements the 5.x TestWatcher interface?

---
misc. links for note-taking/personal aggregation:
- https://github.com/thingsboard/thingsboard/blob/2bd28cb021bc794db5c297cae5063362bee61427/msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractContainerTest.java
- https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/TestWatcher.html
- https://www.baeldung.com/junit-testwatcher
- moving to interface extends implements https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/extension/KitchenSinkExtension.java
- https://stackoverflow.com/questions/49037406/testwatcher-in-junit5
- https://github.com/junit-team/junit5/blob/4262eb8dac61de67feaa9faab5fb8bed764d9c85/documentation/src/docs/asciidoc/user-guide/extensions.adoc
- https://junit.org/junit5/docs/current/user-guide/#extensions

**Comment by aegershman** [comment]
Links related to how a static field within an extension would need to be handled. Woof. Maybe this could be a separate goal...
- https://junit.org/junit5/docs/5.1.1/api/org/junit/jupiter/api/extension/RegisterExtension.html
- https://stackoverflow.com/questions/58632756/is-it-possible-to-make-a-junit5-extension-implement-an-interface-that-is-fulfill
- https://www.baeldung.com/junit-5-registerextension-annotation

**Comment by aegershman** [comment]
Fun fact: `TestWatcher someWatcher = new TestWatcher() { ... // class body here }` is captured under `visitNewClass` rather than `visitClassDeclaration`. Will update later.

**Comment by sambsnyd** [comment]
There's only one project in 77 in our saas (aside from the JUnit 4 project itself) that uses TestWatchers right now, I don't think we need to pursue this at the moment.
