### ISSUE TITLE
ExpectedException to assertThrows does not convert when parameter is hamcrest matcher

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#72]
discovered while applying `org.openrewrite.java.spring.Boot2JUnit4to5Migration` to spring-cloud-consul
https://github.com/spring-cloud/spring-cloud-consul/blob/1da019c336fee08be42347e6f17a8664e81045e1/spring-cloud-consul-binder/src/test/java/org/springframework/cloud/consul/binder/config/ConsulBinderConfigurationTests.java#L39-L48
```
...
import static org.hamcrest.Matchers.containsString;
...
public class ConsulBinderConfigurationTests {
@Test
@Disabled
    void consulBinderDisabledWorks() {
		this.exception.expectMessage(containsString("no proper implementation found"));
		new SpringApplicationBuilder(Application.class).initializers(new ConsulTestcontainers())
				.properties("spring.cloud.consul.binder.enabled=false").run();
	}
```

**Comment by aegershman** [comment]
I believe the root of this problem is that `ExpectedException` used in `assertThrows` should actually be written in a way that has the assertion message asserted against independently using an `assertThat` rather than as the third argument to the `assertThrows` lambda. It's possible that third argument in the lambda isn't performing a check against the assertion message.

see: https://stackoverflow.com/questions/40268446/junit-5-how-to-assert-an-exception-is-thrown
see: https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions
see: https://github.com/openrewrite/rewrite-testing-frameworks/pull/88

not taking this issue at the moment, but am putting a test / some links on it.
